### ISSUE TITLE
Pull Request light doesn't light up on this lab

### ISSUE THREAD

**Issue by faiyamTestFS32** [learn-co-curriculum/ttt-5-move-rb#12]
All my tests are passing locally on Nitrous and I've both used "learn submit" in nitrous and created a pull request manually in Github. Still the Pull request light doesn't light up on this lab. What's going on here? (This is faiyam)

![image](https://cloud.githubusercontent.com/assets/15016713/10434431/7ef9cbe0-70e7-11e5-925f-d8414c928467.png)

Everything passing, and I've learn submitted:

![image](https://cloud.githubusercontent.com/assets/15016713/10434441/9268cf5a-70e7-11e5-9318-e7ed5d4a4cc0.png)

Submitted pull request:

![image](https://cloud.githubusercontent.com/assets/15016713/10434457/a56a2e32-70e7-11e5-97b0-4b8b4a49d696.png)

**Comment by playto** [comment]
I had the same problem on another lesson. I refreshed the learn.co page and then the Pull Request light lit up.
