### ISSUE TITLE
Hi, instructor

### ISSUE THREAD

**Issue by willg1** [learn-co-curriculum/ttt-5-move-rb#14]
I have a program that does what's ask. Made it to 16 examples, 4 failures. But my program does doCLI ask a user for input, pass the user input, calls display. If you can llok at the code give some feedback, would appreciate.

**Comment by AnnJohn** [comment]
Hi @willg1 sorry for the delay on this. If this is still an issue, please use the Ask a Question tool in Learn and someone from our support team will help you out right away. Thanks!
