### ISSUE TITLE
There is a difference in test 02_cli_spec.rb file between the cloned local copy and master origin file.

### ISSUE THREAD

**Issue by subratrout** [learn-co-curriculum/ttt-5-move-rb#15]
1. My original test file did not have the following line:
   allow(self).to receive(:display_board)
2. and then the  .at_least(:once) was missing for which I was not able to pass the test.
   expect(self).to receive(:display_board).with(["X", " ", " ", " ", " ", " ", " ", " ", " "]).at_least(:once)

After I added the 1st line and changed the 2nd line all my tests passed.
I am not sure why.

**Comment by mendelB** [comment]
Hey @subratrout The specs have since been updated to include those lines. Thanks for the input!
