### ISSUE TITLE
learn open not cd to current lesson in Nitrous

### ISSUE THREAD

**Issue by theEricDevelops** [learn-co-curriculum/ttt-5-move-rb#18]
While the `learn open` function is properly forking the lesson, it doesn't change into the appropriate directory after doing so. On my Nitrous IDE, I just executed `learn open` which should have brought me into the "ttt-5-move-rb folder," but instead it dropped me into "interpolation-super-power-q-000."

**Comment by AnnJohn** [comment]
Sorry for the issue you're having. Since this looks like a bug, could you file a bug report for this, which you can do within Learn? Thanks!
