### ISSUE TITLE
Nitrous open

### ISSUE THREAD

**Issue by alicaz** [learn-co-curriculum/ttt-5-move-rb#28]
Hei,
Nitrous open button in the top right corner of the page does not work for me, it races an issues when i press it.

**Comment by AnnJohn** [comment]
hi @alicaz we're moving away from Nitrous to an IDE that we developed in-house. If you go to learn.co/ide you should be able to download it and if you have questions or issue specific to opening labs you can also email support+ide@learn.co

Thanks!
