### ISSUE TITLE
Intro to ruby seset

### ISSUE THREAD

**Issue by backpackwithjets** [learn-co-curriculum/ttt-5-move-rb#29]
I had to take an extended break from the intro to Ruby. Is there any way I can start over/have it reset?

Thank you

**Comment by aturkewi** [comment]
Hey @backpackwithjets this can be done easily enough. The best thing to do is to go to your github page and delete all the labs you have on there (you'll have to click on the lab, click on the little gear, and then look for the delete repo option). 

Then just go back to the start of your Learn track and start working through everything one at a time again :)

If you need a hand with this, please feel free to use the Ask A Question button in Learn or reach out to me on Slack, I am `@avidor`. (If your not on Slack, look through your past emails from Learn and find the invitation for it and log in! All of the Learners are on Slack and there is a great community in there).
