### ISSUE TITLE
learn IDE bug

### ISSUE THREAD

**Issue by IsuruV** [learn-co-curriculum/ttt-5-move-rb#32]
Does not open the needed files for the questions. Shows the correct learn directory, but there are no files in the labs folder. This is a constant issue I have been dealing with the previous questions as well. I usually have to manually unfork, fork, clone..etc a number of times, through git commands to get it to work.

**Comment by AnnJohn** [comment]
hi @IsuruV sorry for the delay. we use this space specifically for issues related to curriculum content so for this issue, could you actually file a bug report or use the Ask a Question tool? thanks
