### ISSUE TITLE
Might want to clarify pass by reference for arrays

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/ttt-5-move-rb#4]
I originally wrote my move function to:
1. take an array as input
2. change one of its values
3. and then end by returning the now-changed array

but this messed up the CLI test suite because apparently arrays in Ruby behave in a 'pass by reference' way, which i didn't know. 

Not sure if/how to make that clearer here, or if it's necessary but just noting my trouble point.

**Comment by matbalez-zz** [comment]
not technically pass by reference but reference types, or whatever. i mean, i understand pass by reference and pass by type, but this particularly subtlety is still murky to me

**Comment by aviflombaum** [comment]
Great tip.

**Comment by aviflombaum** [comment]
closed 9fdac9a
