### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by hvanderloop** [learn-co-curriculum/ttt-5-move-rb#42]
This paragraph really confused me and held up my progress: 

Regarding the player's input: if the user's input is "5", the player wants to fill out position 5 with their character. This means that your method must fill out the correct array index with the player's character.
The player's input is the string '5'. The first thing you'll need to do is convert the string to its integer value, because array indexes are always integers (think '5' vs 5). Give #to_i a try, as in '5'.to_i.

I interpreted this as the input literally was a string, and we would need to convert it first.  Maybe I was just missing the point, as I knew the input is actually a variable, but this paragraph convinced me otherwise.

**Comment by aviflombaum** [comment]
Fixed bfc9631
