### ISSUE TITLE
Not Getting Credit for "Tic Tac Toe Move" Lab

### ISSUE THREAD

**Issue by ejimen** [learn-co-curriculum/ttt-5-move-rb#47]
Hello. I completed this lab, but it does not show like I passed it under my "Curriculum". It's causing to not let me pass my "Command Line Application" section. Please help. Thank you!

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.) If Learn is misbehaving, please direct your bug report to bugs@learn.co.

Engineer Note: This issue may be related to a [currently filed bug](https://flatiron.atlassian.net/browse/LABSBOARD-938).

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
