### ISSUE TITLE
Having an issue with Tic Tac Toe Move

### ISSUE THREAD

**Issue by Apach317** [learn-co-curriculum/ttt-5-move-rb#48]
Receiving the following message: ./bin/move executing a CLI Application
  defines a board variable
  prints "Welcome to Tic Tac Toe!"
  asks the user for input
  converts the users input to an index
  calls move passing the index (FAILED - 1)
Failures:
  1) ./bin/move executing a CLI Application calls move passing the index
     Failure/Error: run_file("./bin/move")
       #<RSpec::ExampleGroups::BinMoveExecutingACLIApplication:0x00000003016960> received :move with unexpected arguments
         expected: (anything, 0, *(any args))
              got: ([" ", " ", " ", " ", " ", " ", " ", " ", " "], 1, "X")
     # ./spec/spec_helper.rb:17:in `run_file'
     # ./spec/spec_helper.rb:6:in `eval'
     # ./spec/spec_helper.rb:6:in `run_file'
     # ./spec/03_cli_spec.rb:48:in `block (2 levels) in <top (required)>'
Finished in 0.03516 seconds (files took 0.11825 seconds to load)
17 examples, 1 failure
Failed examples:
rspec ./spec/03_cli_spec.rb:41 # ./bin/move executing a CLI Application calls move passing the index

Here is my code:

puts "Welcome to Tic Tac Toe!"
board = [" ", " ", " "," ", " ", " "," ", " ", " "]
puts "Where would you like to go?"

input = gets.strip
index = input_to_index(input)
move(board, index)
display_board(board)

**Comment by cjbrock** [comment]
Hey @Apach317!

It looks like this isn't a bug in the curriculum, but a misunderstanding you
have with the material. That's no problem though! Go ahead and hit the Ask A
Question button on learn.co. Either a community member or a technical coach
will be able to help you understand this stuff.

// <3 Corinna
