### ISSUE TITLE
Was never told how to convert string to integer

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/ttt-5-move-rb#5]
I was surprised to learn that I had to cast the the string I get from the `gets` to an integer in order to use it as an index into the array. I don't think the material to date has covered `to_i`? But even if it did previously, I've probably forgotten and lab should remind me to think about this, else I predict this will be a common error.

**Comment by aviflombaum** [comment]
0de9088 closes

great tip!
