### ISSUE TITLE
Potential typos

### ISSUE THREAD

**Issue by mdanapalmer** [learn-co-curriculum/ttt-5-move-rb#50]
Hello my dears!  I am hoping to enrich the program by finding the small tidbits I missed the first time round.  I believe there are some missing words in one of the instructions under the #move method instructions on the following page: https://learn.co/tracks/full-stack-web-development-v6/intro-to-ruby-development/command-line-applications/tic-tac-toe-move?batch_id=306&track_id=43149

I believe the text should say: When collection objects are passed into methods, and those collection objects are changed within those methods the change is made _to_ the collection directly.

Also: It is not made to a copy like _what_ happens when a Number is passed. 

Aysan requested I raise the issue to have this resolved.  Thank you very kindly for your efforts, they're super appreciated!

Best!

Dana

**Comment by sgharms** [comment]
Thanks for the keen eye! Amended!
