### ISSUE TITLE
tests break when variable overwritten

### ISSUE THREAD

**Issue by jd2rogers2** [learn-co-curriculum/ttt-5-move-rb#51]
worked with a student today who had the following in her /bin/move which is not incorrect ruby but it was breaking the get_variable_from_file method in the helper
tried to pry in and found that `file_scope.eval` wasn't liking that but i don't know a fix
below code passes all tests with `      board = move(board, position, player = "X")` changed to `      move(board, position, player = "X")`

```
#!/usr/bin/env ruby
require_relative '../lib/move.rb'
require 'pry'

# Code your CLI Here
  puts "Welcome to Tic Tac Toe!"
  board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
  display_board(board)

  # while board[0..8].include?(" ")

    puts "Where do you want to go?"
    puts "Please enter a whole number from one to nine inclusive"
    input = gets.strip
      # break if input == "stop"

    position = input_to_index(input)
    if position != -1
      board = move(board, position, player = "X")
      display_board(board)
    end
  # end
```

**Comment by drakeltheryuujin** [comment]
Hi @jd2rogers2,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
