### ISSUE TITLE
Where to start...

### ISSUE THREAD

**Issue by brianacooke** [learn-co-curriculum/ttt-5-move-rb#52]
Hello!

I have read the tutorial but the last part titled "Continuing to Solve Fizzbuzz" is confusing. Am I supposed to copy that code? 

I tried this:

def fizzbuzz(int)
  if int % 3 == 0 # if the number int is divisible by 3
      "Fizz"
end

def fizzbuzz(int)
  if int % 5 == 0
    "Buzz"
  end

def fizzbuzz(int)
  if int % 3 == 0
  elsif int % 5 == 0
      "Fizzbuzz"
    end

And when running learn I got in the terminal:

// ♥ learn
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load': /home/creative-kernel-3560/rspec
-fizzbuzz-online-web-sp-000/fizzbuzz.rb:18: syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'

I'm not sure what this means..

**Comment by brianacooke** [comment]
Update: I figured it out!

**Comment by maxwellbenton** [comment]
Hi @brianacooke,

Glad to hear you have figured it out! Looks like it was a syntax error that was breaking the code before the tests could fully run. Great work on figuring it out!

As this is resolved, I am closing the issue.
